tag-name = "v$VERSION"
tarball-location = []
release-timeout = 5

[[update_version]]
path = "setuptools_protobuf/__init__.py"
match = "^__version__ = ((.*))$"
new-line = "__version__ = $TUPLED_VERSION"
